### ISSUE TITLE
Liquid Exception: Liquid syntax error: unknown tag 'calendar'

### ISSUE THREAD

**Issue by PhictionalOne** [Rakefire/jekyll-ical-tag#1]
Hi,
I got the Exception mentioned above while `bundle exec jekyll serve`.
I just copied your example code after doing the steps in the Readme.md

Greetings
Gilgamensch

**Comment by rickychilcott** [comment]
Thanks for reporting @ST0PPELB4RT 

I created an example project at https://github.com/Rakefire/jekyll-ical-tag-test and found the issue. I updated the liquid tag name from `calendar` to `ical` and didn't update the readme.

I fixed this in c4037ee6306e8f40680151e899d8eb9ca9ce3645 and it's live now.

**Comment by PhictionalOne** [comment]
Thanks for the quick fixing 👍
