### ISSUE TITLE
Printing `event.excerpt` sometimes produces a string, other times an array depending on event data

### ISSUE THREAD

**Issue by fabacab** [Rakefire/jekyll-ical-tag#28]
Similar to what's described in #25, when trying to print a given event's `excerpt` (as opposed to its `content` or `description`), which I believe is a member property automatically generated by part of Jekyll core, templates don't always produce expected results. Specifically, in the exact same situations as described in the issue cited earlier, printing an `event.excerpt` from within an `ical` tag loop will print an array, complete with square brackets (`["content of excerpt…"`)  rather than the simple `string` as expected. For example, with [the Sereno Regis test iCalendar](https://github.com/Rakefire/jekyll-ical-tag/blob/master/spec/support/serenoregis.ics) file:

```
{% ical url: https://github.com/Rakefire/jekyll-ical-tag/raw/master/spec/support/serenoregis.ics %}
* {{ event.excerpt }}
{% endical %}
```

produces HTML, in part, like this:

```html
<li>[“Il 29 novembre \xC3\xA8 una data importante per il popolo Palestinese. \nIn questa data nel 1947, l\xE2\x80\x99Assemblea Generale delle Nazioni Unite adott\xC3\xB2 una risoluzione chiamata \xE2\x80\x9Cil piano di partizione\xE2\x80\x9D che divideva la Palestina in uno Stato Ebraico e uno Stato Arabo.\nA seguito di questa risoluzione, pi\xC3\xB9 di 700,000 Palestinesi scapparono…</li>
```

when the expected output should simply have been something more like:

```html
<li>Il 29 novembre…</li> <!-- Etc., and encoded correctly. -->
```

**Comment by rickychilcott** [comment]
Hey @fabacab. Check out version 1.3 of the gem

I think I fixed this issue in 54dc4ccb9079f86b0225388be187d681b65dfb80 by preprocessing all property values that are array-like to be strings. Let me know if this fixes your issue.

The thing I'm not sure about is the `excerpt` property in your example doesn't appear to exist?

When I tried:

```
{% ical url: https://github.com/Rakefire/jekyll-ical-tag/raw/master/spec/support/serenoregis.ics %}
* {{ event.excerpt }}
{% endical %}
```

It was blank because there is no excerpt property. Did you mean `summary` or `description`?

Either way, the underlying issue should be addressed, but let me know if not.

**Comment by fabacab** [comment]
> Did you mean `summary` or `description`?

Y'know, I probably did, although I'm sure I was dealing with excerpts when I wrote this.

> Either way, the underlying issue should be addressed, but let me know if not.

It does indeed appear to be resolved. All my various templates are producing the output I expect them to, now. Thanks again for nailing this down so quickly. :)

**Comment by rickychilcott** [comment]
No problem. Thanks for working to make this plug-in better!
