### ISSUE TITLE
reverse: flag does not reverse order.

### ISSUE THREAD

**Issue by Willsie-Digital** [Rakefire/jekyll-ical-tag#32]
Using an ICS link from Sesh (https://sesh.fyi/calendar/98AtNsUKcpeFsCGzc8Zeie.ics for reference)  where start time is indeed unique for multiple events the reverse flag in the ical plugin does not actually reverse the order of the posts.

**Comment by rickychilcott** [comment]
Version 1.3.3 should fix it
