### ISSUE TITLE
Variables in Tag

### ISSUE THREAD

**Issue by c-leitner** [Rakefire/jekyll-ical-tag#40]
I am not sure if it is possible but I can't get variable passing to work. I am trying to pass the "after_date:" as a variable.
`{% ical url: https://example.com/test.ics reverse: false after_date: someVariableWithDate %}`
When entering a date into the tag it works just fine, with a variable it does not work.
This would make it a lot easier to "dynamically" change the displayed output.

**Comment by rickychilcott** [comment]
Hello. We do support variables for the URL, but I don't think we do for some of the other fields. Liquid variables are annoying but super useful.

I'm using this plugin for one client, but haven't been doing anything in jekyll lately. I've moved to Bridgetown for my projects, but I'm happy to keep supporting this.

Are you interested in shooting for a PR or do you have no idea on where to begin? I'm happy to provide you a few examples in some other plugins I'm working on that might help you.

**Comment by c-leitner** [comment]
Unfortunately I am not very proficient in ruby, but I added it. There is for sure a cleaner way of doing it .

**Comment by rickychilcott** [comment]
V1.4.0 should have the fix. Let me know if it doesn't work for you.
